version: "3.9"

services:
  web:
    build: .
    command: uvicorn reputeai.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./reputeai:/app/reputeai
    ports:
      - "8000:8000"
    env_file: .env.example
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reputeai
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A reputeai.app.workers.celery_app worker --loglevel=info
    volumes:
      - ./reputeai:/app/reputeai
    env_file: .env.example
    depends_on:
      - redis
  beat:
    build: .
    command: celery -A reputeai.app.workers.celery_app beat --loglevel=info
    volumes:
      - ./reputeai:/app/reputeai
    env_file: .env.example
    depends_on:
      - redis
